### ISSUE TITLE
error while compress video

### ISSUE THREAD

**Issue by deepakpanchal-silverwing** [ChanNagihong/VideoCompressor#2]
OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 7) = {
      int32_t color-format = 2130708361
      int32_t i-frame-interval = 3
      string mime = "video/avc"
      int32_t width = 1280
      int32_t bitrate = 1280000
      int32_t frame-rate = 30
      int32_t height = 720
      int32_t encoder = 1
    }
Error

    java.lang.UnsupportedOperationException: Audio sample rate conversion not supported yet.
        at com.nagihong.videocompressor.audioProcessor.AudioProcessor.setActualDecodedFormat(AudioProcessor.java:74)
        at com.nagihong.videocompressor.trackTranscoder.AudioTrackTranscoder.drainDecoder(AudioTrackTranscoder.java:166)
        at com.nagihong.videocompressor.trackTranscoder.AudioTrackTranscoder.stepPipeline(AudioTrackTranscoder.java:115)
        at com.nagihong.videocompressor.transcoder.VideoCompressEngine.stepPipeline(VideoCompressEngine.java:193)
        at com.nagihong.videocompressor.transcoder.VideoCompressEngine.runPipelines(VideoCompressEngine.java:167)
        at com.nagihong.videocompressor.transcoder.VideoCompressEngine.transcodeVideo(VideoCompressEngine.java:73)
        at com.nagihong.videocompressor.VideoCompressor.compressVideo(VideoCompressor.java:18)
        at com.nagihong.videocompressor.VideoCompressor.compressVideo(VideoCompressor.java:12)

**Comment by ChanNagihong** [comment]
Would you mind tell me your device model, and Android OS version?

**Comment by ChanNagihong** [comment]
This project was deprecated from now on, I suggest you try Transcoder(https://github.com/natario1/Transcoder), maybe it can help you.

**Comment by deepakpanchal-silverwing** [comment]
Thanks
